### ISSUE TITLE
Expand Bug ?

### ISSUE THREAD

**Issue by LucaGabi** [voronov-maxim/OdataToEntity#34]
Hi,

I have this code:
```
using GomoiuWeb.Base;
using GomoiuWeb.Shared.Data.DB;
using OdataToEntity;
using OdataToEntity.EfCore;
using System;
using System.IO;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace ODat
{
    class Program
    {
        static async Task Main(string[] args)
        {
            Global.DefaultConnectionString = "...";
            //Create adapter data access, where OrderContext your DbContext
            var dataAdapter = new OeEfCoreDataAdapter<AppDB>();
            //Create query parser
            var parser = new OeParser(new Uri("http://dummy"), dataAdapter.BuildEdmModelFromEfCoreModel());
            //Query
            var uri = new Uri("http://dummy/Doctors?$select=Name&$expand=ClientAppointments");
            //The result of the query
            var response = new MemoryStream();
            //Execute query
            await parser.ExecuteGetAsync(uri, OeRequestHeaders.JsonDefault, response, CancellationToken.None);

            Console.WriteLine(Encoding.ASCII.GetString(response.ToArray()));

            Console.ReadKey();
        }
    }
}
```
And I get an exception with the $expand:
```
"System.InvalidOperationException: Nullable object must have a value.\r\n   at lambda_method(Closure , ClientAppointments )\r\n   at System.Linq.Internal.Lookup`2.CreateForJoinAsync(IAsyncEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer, CancellationToken cancellationToken)\r\n   at System.Linq.AsyncEnumerable.GroupJoinAsyncEnumerable`4.GroupJoinAsyncEnumerator.MoveNext(CancellationToken cancellationToken)\r\n   at System.Linq.AsyncEnumerable.SelectManyAsyncIterator`3.MoveNextCore(CancellationToken cancellationToken)\r\n   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken)\r\n   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken)\r\n   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken can
cellationToken)\r\n   at OdataToEntity.Db.OeDbEnumerator.MoveNextAsync() in D:\\programming\\OdataToEntity\\source\\OdataToEntity\\Db\\OeDbEnumerator.cs:line 134\r\n   at OdataToEntity.Writers.OeGetWriter.GetWriter.SerializeAsync(OeEntryFactory entryFactory, OeAsyncEnumerator asyncEnumerator, OeQueryContext queryContext) in D:\\programming\\OdataToEntity\\source\\OdataToEntity\\Writers\\OeGetWriter.cs:line 129\r\n   at OdataToEntity.Writers.OeGetWriter.SerializeAsync(OeQueryContext queryContext, OeAsyncEnumerator asyncEnumerator, String contentType, Stream stream) in D:\\programming\\OdataToEntity\\source\\OdataToEntity\\Writers\\OeGetWriter.cs:line 246\r\n   at OdataToEntity.OeGetParser.ExecuteAsync(ODataUri odataUri, OeRequestHeaders headers, Stream stream, CancellationToken cancellationToken) in D:\\programming\\OdataToEntity\\source\\OdataToEntity\\Parsers\\OeGetParser.cs:line 120\r\n   at OdataToEntity.OeParser.ExecuteQueryAsync(ODataUri odataUri, OeRequestHeaders headers, Stream responseStream, Cancellat
ionToken cancellationToken) in D:\\programming\\OdataToEntity\\source\\OdataToEntity\\Parsers\\OeParser.cs:line 113\r\n   at OdataToEntity.OeParser.ExecuteGetAsync(Uri requestUri, OeRequestHeaders headers, Stream responseStream, CancellationToken cancellationToken) in D:\\programming\\OdataToEntity\\source\\OdataToEntity\\Parsers\\OeParser.cs:line 108\r\n   at ODat.Program.Main(String[] args) in C:\\Work\\gomoiu\\ODat\\Program.cs:line 27\r\n   at ODat.Program.<Main>(String[] args)"
```
Is this a bug or I should configure something to get it to work?

Thanks.

**Comment by voronov-maxim** [comment]
Possible client evaluation like https://github.com/aspnet/EntityFrameworkCore/issues/11567
For help please send the code reproducing bug

**Comment by LucaGabi** [comment]
Thanks, the error was caused by a null value in the ClientAppointments many to many link table. 
After fixing that, using expand generates an emty array.

This is done using EF Core 2.1 where you need a mapping table for many to many relations. 
How to  use expand in this case ? Can this be done ?

Query: 
http://dummy/Doctors?$expand=ClientAppointments&$select=Name,ClientAppointments
Result:
```
{
    "@odata.context": "http://dummy/$metadata#Doctors(Name,ClientAppointments,ClientAppointments())",
    "value": [
        {
            "Name": "Ioana",
            "ClientAppointments": []
        },
        {
            "Name": "Dr Felicia Cora ",
            "ClientAppointments": []
        },
        {
            "Name": "Dr Mirela Iancu",
            "ClientAppointments": []
        },
        {
            "Name": "Dr Daniela Popeia ",
            "ClientAppointments": []
        },
        {
            "Name": "Dr Daniela Lescae ",
            "ClientAppointments": []
        },
        {
            "Name": "Dr Diana Zaharia ",
            "ClientAppointments": []
        },
        {
            "Name": "Dr Ioana Adriana Ghiorghiu ",
            "ClientAppointments": []
        },
        {
            "Name": "Dr Alina Cavache",
            "ClientAppointments": []
        },
        {
            "Name": "Dr. S\u0103l\u0103v\u0103stru George Andrei ",
            "ClientAppointments": []
        },
        {
            "Name": "Dr. Avram Anca Ioana ",
            "ClientAppointments": []
        }
    ]
}
```

**Comment by voronov-maxim** [comment]
https://github.com/voronov-maxim/OdataToEntity/wiki/Many-to-many-relationships-(without-CLR-class-for-join-table)
Customer - Doctor
CustomerShippingAddress - ClientAppointment
ShippingAddress - Appointment

For help please send  c# classes: Doctor, ClientAppointment, Appointment

**Comment by LucaGabi** [comment]
------deleted -----------
Thanks!

1. GomoiuWeb.Shared is the lib with DbContext
2. ODat is the console test with OData lib

Zip files have the source not the bin.

I'll have to delete the files after you'll download

**Comment by LucaGabi** [comment]
I don't use attributes on pocos in EF Core dose it work without them?

**Comment by LucaGabi** [comment]
.. I was wrong, the relation between Doctors and ClientAppointments is 1-m

**Comment by LucaGabi** [comment]
This dose not work with ef core many to many mapping table.. Maybe you can create a small sample for ef core if it dose work and I can't make it work.. It would be very useful.

**Comment by voronov-maxim** [comment]
Please find test repository https://github.com/voronov-maxim/Doctors.git
there expand works fine

**Comment by LucaGabi** [comment]
Thanks. 

You are correct it dose work but there is a bug not being able to select only the navigation property in the expanded relation.

This:
http://dummy/Doctors?$expand=DoctorSpecializations($select=Specialization)&$select=Name
Gives:

```
{
    "@odata.context": "http://dummy/$metadata#Doctors(Name,DoctorSpecializations(Specialization))",
    "value": [
        {
            "Name": "Ioana",
            "DoctorSpecializations": []
        },
        {
            "Name": "Dr Felicia Cora ",
            "DoctorSpecializations": [
                {
                    "CreatedAt": "2019-04-24T08:56:15Z",
                    "CreatedBy": "0df6e890-8524-4e0a-bd00-6661ae0ae591",
                    "DeletedAt": null,
                    "DeletedBy": null,
                    "DoctorId": 6,
                    "SpecializationId": 5,
                    "UpdatedAt": null,
                    "UpdatedBy": null,
                    "Specialization": {
                        "CreatedAt": "2019-04-15T14:22:33Z",
                        "CreatedBy": "96a93e63-51c2-417e-9e35-4e2e2a5d459b",
                        "DeletedAt": null,
                        "DeletedBy": null,
                        "Description": "medic sef sectie",
                        "Id": 5,
                        "Name": "medic sef sectie",
                        "PageId": null,
                        "UpdatedAt": null,
                        "UpdatedBy": null,
                        "Url": null
                    }
                }
            ]
        }
    ]
}
```
But adding a field like DoctorId:
http://dummy/Doctors?$expand=DoctorSpecializations($select=DoctorId,Specialization)&$select=Name
is correct, it returns only that field and the nav. prop.

```
{
    "@odata.context": "http://dummy/$metadata#Doctors(Name,DoctorSpecializations(DoctorId,Specialization))",
    "value": [
        {
            "Name": "Ioana",
            "DoctorSpecializations": []
        },
        {
            "Name": "Dr Felicia Cora ",
            "DoctorSpecializations": [
                {
                    "DoctorId": 6,
                    "Specialization": {
                        "CreatedAt": "2019-04-15T14:22:33Z",
                        "CreatedBy": "96a93e63-51c2-417e-9e35-4e2e2a5d459b",
                        "DeletedAt": null,
                        "DeletedBy": null,
                        "Description": "medic sef sectie",
                        "Id": 5,
                        "Name": "medic sef sectie",
                        "PageId": null,
                        "UpdatedAt": null,
                        "UpdatedBy": null,
                        "Url": null
                    }
                }
            ]
        }
    ]
}
```

**Comment by LucaGabi** [comment]
It is of good value anyway so thanks for the great work.

Dose this support insert, update, and delete statements ?

**Comment by voronov-maxim** [comment]
https://github.com/voronov-maxim/OdataToEntity/issues/34#issuecomment-497975262
This bug in version 2.3.0 has been fixed.

Insert, update, delete https://github.com/voronov-maxim/OdataToEntity/wiki/OData-batch-request

**Comment by LucaGabi** [comment]
Use the same db and data if it helps to see query result.
[sql.zip](https://github.com/voronov-maxim/OdataToEntity/files/3244506/sql.zip)

I've tested with 2.3.0 and the problem is still there for this query:
http://dummy/Doctors?$filter=DoctorSpecializations/any()&$expand=DoctorSpecializations($select=Specialization;$expand=Specialization($select=Name))&$select=Name

If I add an SpecializationId it works:
http://dummy/Doctors?$filter=DoctorSpecializations/any()&$expand=DoctorSpecializations($select=SpecializationId,Specialization;$expand=Specialization($select=Name))&$select=Name


In .csproj:
```
  <ItemGroup>
    <PackageReference Include="OdataToEntity" Version="2.3.0" />
    <PackageReference Include="OdataToEntity.EfCore" Version="2.3.0" />
  </ItemGroup>
```

**Comment by LucaGabi** [comment]
In what way is the "help wanted" meant ?

**Comment by voronov-maxim** [comment]
I did not correctly understand the meaning of the phrase "help wanted" as "i helped you"

**Comment by voronov-maxim** [comment]
Fix: 'Nullable object should be set to', now can use 'expand' without '$filter=DoctorSpecializations/any()'.
Fix: Select only the navigation property.

**Comment by LucaGabi** [comment]
Works great!
